# Uncomment the next line to define a global platform for your project
# platform :ios, '14.3'

target 'Movieee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movieee

  target 'MovieeeTests' do
    inherit! :search_paths
  # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
